language: python
sudo: false
python:
  - "3.6"

install:
  - "pip install -r ./requirements.txt"
  - "pip install -r ./tests/requirements.txt"

script:
  - "py.test . -v --cov . --cov-report term-missing"

after_success:
  - "coveralls"

env:
  - PYTHONPATH=.
